version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/shankari/everest-demo/mqtt-server:build_pkg_add-15118-dash-2-logs-to-dc-demo
    logging:
      driver: none

  manager:
    image: ghcr.io/shankari/everest-demo/manager:build_pkg_add-15118-dash-2-logs-to-dc-demo
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    entrypoint: "sh ./build/run-scripts/run-sil-two-evse.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  node-red:
    image: ghcr.io/shankari/everest-demo/nodered:build_pkg_add-15118-dash-2-logs-to-dc-demo
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-two-evse-flow.json
    ports:
      - 1880:1880
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
