name: cicd

on:
  push:
    branches:
      - 'build_pkg_**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker-build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - image: ghcr.io/us-joet/everest-demo/manager
            context: ./manager
          - image: ghcr.io/us-joet/everest-demo/mqtt-server
            context: ./mosquitto
          - image: ghcr.io/us-joet/everest-demo/nodered
            context: ./nodered

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into GitHub container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
