name: e2etest

on:
  pull_request:
    branches:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * *'

jobs:
  pull-and-run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Setup Docker on macOS using Colima, Lima-VM, and Homebrew.
        uses: douglascamata/setup-docker-macos-action@v1-alpha # Uses an action in the root directory
        id: docker-install
      - name: Verify install
        id: docker-verify
        shell: bash
        run: |
          docker --version
          docker compose --version
      - name: Download and launch
        id: curl-download-and-launch
        shell: bash
        timeout-minutes: 20
        run: |
          curl https://raw.githubusercontent.com/everest/everest-demo/main/demo-iso15118-2-ac-plus-ocpp201.sh | bash
