name: e2etest

on:
  # Adding this to indicate that this workflow will be triggered from another workflow
  workflow_dispatch:
    inputs:
      parent_workflow:
        description: "Name of the parent workflow that triggered this workflow"
        required: true
      event_name:
          description: "Event type that triggered this workflow (e.g. push, pull_request)"
          required: true

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * *'

jobs:
  pull-and-run-tests:
    if: github.event.inputs.parent_workflow == 'cicd.yaml' && github.event.inputs.event_name != 'pull_request'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:

      - name: Verify parent workflow name
        id: verify-parent-workflow
        run: |
          echo "Workflow triggered by parent workflow: ${{ github.event.inputs.parent_workflow }}"

      - name: Setup Docker on macOS using Colima, Lima-VM, and Homebrew.
        id: docker-install
        if: matrix.os == 'macos-13'
        uses: douglascamata/setup-docker-macos-action@v1-alpha # Uses an action in the root directory
        
      - name: Verify install for both macOS and Ubuntu
        id: docker-verify
        shell: bash
        run: |
          docker --version
          docker compose version
          if [ "$RUNNER_OS" == "macOS" ]; then
            colima --version
            mkdir -p /var/folders
          fi

      - name: Download and launch automated-testing.sh
        id: curl-download-and-launch-automated-testing
        shell: bash
        timeout-minutes: 60
        run: |
          curl https://raw.githubusercontent.com/everest/everest-demo/main/demo-automated-testing.sh | bash
          # curl https://raw.githubusercontent.com/everest/everest-demo/main/demo-iso15118-2-ac-plus-ocpp201.sh | bash
          