name: e2etest

on:
  pull_request:
    branches: [ automate-tests-merge ]
  push:
    branches: [ automate-tests-actions, automate-tests-merge ]

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * *'

jobs:
  pull-and-run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - name: Setup Docker on macOS using Colima, Lima-VM, and Homebrew.
        id: docker-install
        if: matrix.os == 'macos-13'
        uses: douglascamata/setup-docker-macos-action@v1-alpha # Uses an action in the root directory

      - name: Print action outputs containing docker version
        id: print-outputs
        run: |
          echo "Docker client version: ${{ steps.docker-install.outputs.docker-client-version}}"
          echo "Docker compose version: ${{ steps.docker-install.outputs.docker-compose-version}}"
        
      - name: Verify install for both macOS and Ubuntu
        id: docker-verify
        shell: bash
        run: |
          docker --version
          docker compose version
          if [ "$RUNNER_OS" == "macOS" ]; then
            colima --version
            mkdir -p /var/folders
          fi

      - name: Download and launch automated-testing.sh
        id: curl-download-and-launch-automated-testing
        shell: bash
        timeout-minutes: 30
        run: |
          curl https://raw.githubusercontent.com/everest/everest-demo/main/demo-automated-testing.sh | bash
          # curl https://raw.githubusercontent.com/everest/everest-demo/main/demo-iso15118-2-ac-plus-ocpp201.sh | bash
          